# Generated by Django 5.0.7 on 2024-07-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(unique=True)),
                ('short_code', models.CharField(blank=True, max_length=6, unique=True)),
                ('click_count', models.IntegerField(default=0)),
            ],
        ),
    ]
